# 编译
FROM docker.code.firfe.work/golang:1.26 AS building

# 设置国内镜像源
RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct

# 设置工作目录
WORKDIR /building

# 复制 go.mod 和 go.sum 文件（如果存在）
COPY 代码/go.mod 代码/go.sum ./

# 下载 Go 依赖项，利用 Docker 缓存机制
RUN go mod download

# 复制源代码

COPY 代码 /building

RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frpc -o bin/frpc ./cmd/frpc

# 最终镜像
FROM docker.code.firfe.work/alpine:3.23

# 使用国内镜像源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]

CMD [ "-c", "/frp/frpc.toml" ]
